version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data/pgdata
      - /etc/passwd:/etc/passwd:ro
    ports:
      - "55432:5432"
    restart: "no"
    user: "${UID}:${GID}"
