version: '3.7'

services:
  postgres:
    image: postgres:13.0-alpine
    command: -h 127.0.0.1,::1 -p ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data/pgdata
      - /etc/passwd:/etc/passwd:ro
    network_mode: host
    restart: 'no'
    user: '${UID}:${GID}'
