#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ ! -s "$SCRIPT_DIR/.vars" ]; then
  echo "Error: file $SCRIPT_DIR/.vars not found or zero size."
  exit 1
fi
source $SCRIPT_DIR/.vars

\docker-compose -f ${SCRIPT_DIR}/docker-compose.yml -p $COMPOSE_PROJECT_NAME $@
